import React, { useEffect } from "react";
import { spacing, text } from "../../styles/tokens";
import { MarketingLayout } from "../marketing/MarketingLayout";

const TermsPage: React.FC = () => {
  useEffect(() => {
    document.title = "Terms of Service — RentChain";
  }, []);

  return (
    <MarketingLayout tone="warmNeutral">
      <div style={{ display: "flex", flexDirection: "column", gap: spacing.md, maxWidth: 760 }}>
        <div>
          <h1 style={{ margin: 0 }}>Terms of Service</h1>
          <div style={{ marginTop: spacing.xs, color: text.subtle }}>Effective date: 2026-01-21</div>
        </div>
        <p style={{ margin: 0, color: text.muted }}>
          These Terms of Service (Terms) govern your use of the RentChain platform and website (the Service). By
          using the Service, you agree to these Terms.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>1) Platform Role</h2>
        <p style={{ margin: 0, color: text.muted }}>
          RentChain provides governed operational infrastructure, workflow tools, and record-keeping support for rental
          operations. RentChain does not make rental decisions, does not provide legal advice, does not operate as a
          consumer reporting agency or credit bureau, does not claim government or institutional approval, and is not
          responsible for landlord or tenant decisions or outcomes.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>2) Lawful Use and Compliance</h2>
        <p style={{ margin: 0, color: text.muted }}>
          You agree to use the Service only for lawful purposes and in compliance with applicable laws, including
          housing and human rights laws, privacy laws, and any consumer reporting or tenant screening requirements.
          Landlords are solely responsible for determining permissible purpose and lawful basis when requesting or
          using screening information.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>3) Screening and Third-Party Services</h2>
        <p style={{ margin: 0, color: text.muted }}>
          Where screening is available, RentChain may facilitate tenant-initiated screening through third-party
          providers. Those providers may maintain their own credentialing, permissible-purpose, and access requirements.
          Outputs are generated by those providers. RentChain does not guarantee the accuracy, completeness, availability,
          bureau access, or approval status of third-party services.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>4) Governance, Consent, and Interoperability</h2>
        <p style={{ margin: 0, color: text.muted }}>
          RentChain supports permissioned workflows, consent-aware governance, audit lineage, review controls,
          evidence references, institutional-readiness workflows, and interoperability governance. These features are
          operational tooling only. They do not create automatic approvals, government submissions, legal certifications,
          autonomous onboarding, uncontrolled external synchronization, or permission to bypass applicable legal,
          provider, or institutional requirements.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>5) User Content and Records</h2>
        <p style={{ margin: 0, color: text.muted }}>
          You are responsible for information you submit, upload, or record through the Service. You represent that
          you have the right to provide such information and that doing so does not violate applicable law or
          third-party rights.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>6) Prohibited Conduct</h2>
        <p style={{ margin: 0, color: text.muted }}>You may not:</p>
        <ul style={{ marginTop: spacing.sm, marginBottom: 0, paddingLeft: "1.1rem", color: text.muted }}>
          <li>Use the Service for discriminatory or unlawful decision-making</li>
          <li>Attempt to access data you are not authorized to access</li>
          <li>Upload malware or abuse platform security</li>
          <li>Misrepresent identity or consent</li>
          <li>Share sensitive screening information without authorization</li>
          <li>Represent RentChain as a credit bureau, government authority, legal authority, or approved institutional gateway</li>
        </ul>

        <h2 style={{ marginTop: spacing.lg }}>7) Service Availability</h2>
        <p style={{ margin: 0, color: text.muted }}>
          The Service is provided as is and as available. We may modify, suspend, or discontinue features at any
          time.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>8) Disclaimers</h2>
        <p style={{ margin: 0, color: text.muted }}>
          To the maximum extent permitted by law, RentChain disclaims warranties of merchantability, fitness for a
          particular purpose, and non-infringement. RentChain does not warrant that the Service will be uninterrupted
          or error-free.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>9) Limitation of Liability</h2>
        <p style={{ margin: 0, color: text.muted }}>
          To the maximum extent permitted by law, RentChain will not be liable for indirect, incidental, special,
          consequential, or punitive damages, or for loss of profits, revenue, data, or goodwill. RentChain's total
          liability for any claim related to the Service will be limited to the amount paid to RentChain in the
          applicable period, if any, except where such limitation is prohibited by law.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>10) Indemnification</h2>
        <p style={{ margin: 0, color: text.muted }}>
          You agree to indemnify and hold RentChain harmless from claims arising out of your misuse of the Service,
          violation of these Terms, or violation of applicable law, including unlawful screening practices or
          unauthorized disclosure of personal information.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>11) Termination</h2>
        <p style={{ margin: 0, color: text.muted }}>
          We may suspend or terminate access to the Service if you violate these Terms or if required for security or
          legal compliance.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>12) Governing Law</h2>
        <p style={{ margin: 0, color: text.muted }}>
          These Terms are governed by the laws applicable to your operating jurisdiction unless otherwise required by
          law. Counsel should confirm the final jurisdiction clause.
        </p>

        <h2 style={{ marginTop: spacing.lg }}>13) Contact</h2>
        <p style={{ margin: 0, color: text.muted }}>support@rentchain.ai</p>
        <p style={{ marginTop: spacing.xs, marginBottom: 0, color: text.muted }}>privacy@rentchain.ai</p>
      </div>
    </MarketingLayout>
  );
};

export default TermsPage;
