steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'rentchain-landlord-api',
        '--source', './rentchain-api',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'COMMIT_SHA=${COMMIT_SHA}',
        '--set-secrets', 'FIREBASE_API_KEY=firebase-web-api-key:latest'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

timeout: '1200s'
