steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        SERVICE="rentchain-landlord-api"
        REGION="us-central1"
        REQUIRED=("JWT_SECRET" "FIREBASE_API_KEY")
        ENV_NAMES="$(gcloud run services describe "$SERVICE" \
          --region "$REGION" \
          --format="value(spec.template.spec.containers[0].env[].name)" \
          | tr ';' '\n' | tr -d '[:space:]' | sed '/^$/d')"

        MISSING=()
        for name in "${REQUIRED[@]}"; do
          if ! grep -qx "$name" <<< "$ENV_NAMES"; then
            MISSING+=("$name")
          fi
        done

        if [ "${#MISSING[@]}" -gt 0 ]; then
          echo "Cloud Run preflight failed. Missing required env names: ${MISSING[*]}"
          exit 1
        fi

        echo "Cloud Run preflight passed."
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        SERVICE="rentchain-landlord-api"
        REGION="us-central1"
        for i in 1 2 3 4 5; do
          echo "Deploy attempt $i..."
          if gcloud run deploy "$SERVICE" \
            --image "us-central1-docker.pkg.dev/project-0d9658de-af29-4dc0-a99/rentchain-api/rentchain-landlord-api:${COMMIT_SHA}" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --quiet; then
            echo "Deploy succeeded"
            exit 0
          fi
          echo "Deploy failed (likely conflict). Sleeping..."
          sleep $((i*5))
        done
        exit 1

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_MEDIUM"

timeout: "1200s"
