import PDFDocument from "pdfkit";
import type { LeaseEvidencePackage, LeaseEvidencePackageSection } from "./leaseEvidencePackageTypes";

const SOURCE_LABELS: Record<string, string> = {
  canonicalEvents: "Audit event",
  events: "Audit event",
  ledgerAttachments: "Document record",
  ledgerEntries: "Payment ledger entry",
  leaseNotices: "Notice record",
  leaseSigningEvents: "Signing event",
  leaseSigningRequests: "Signing request",
  leases: "Lease record",
  maintenanceRequests: "Maintenance request",
  messages: "Message record",
  payments: "Payment record",
  properties: "Property record",
  rentPayments: "Payment record",
  tenants: "Tenant record",
  units: "Unit record",
};

function line(doc: PDFKit.PDFDocument, label: string, value: unknown) {
  doc.font("Helvetica-Bold").text(`${label}: `, { continued: true });
  doc.font("Helvetica").text(String(value ?? "Not recorded"));
}

function sourceLabel(sourceCollection: string): string {
  return SOURCE_LABELS[sourceCollection] || "Source record";
}

function sectionStatus(section: LeaseEvidencePackageSection): string {
  return section.items.length ? `${section.items.length} item${section.items.length === 1 ? "" : "s"}` : "No items";
}

function addWrappedText(doc: PDFKit.PDFDocument, text: string) {
  doc.font("Helvetica").fontSize(9).text(text, {
    lineGap: 2,
    paragraphGap: 3,
  });
}

export async function renderLeaseEvidencePackagePdf(pkg: LeaseEvidencePackage): Promise<Buffer> {
  return await new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "LETTER", margin: 54, compress: false });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.font("Helvetica-Bold").fontSize(18).text(pkg.title);
    doc.moveDown(0.25);
    doc.font("Helvetica").fontSize(11).text(pkg.subtitle || "Lease evidence package");
    doc.moveDown();

    doc.font("Helvetica-Bold").fontSize(12).text("Governance Metadata");
    doc.moveDown(0.25);
    doc.fontSize(9);
    line(doc, "Evidence Package ID", pkg.governance.evidencePackageId);
    line(doc, "Generated By", pkg.governance.generatedBy);
    line(doc, "Generated At", pkg.governance.generatedAt);
    line(doc, "Lease ID", pkg.governance.leaseId);
    line(doc, "Package Type", pkg.governance.packageType);
    line(doc, "Sections Included", pkg.governance.sectionsIncluded.join(", "));
    doc.moveDown();

    for (const section of pkg.sections) {
      if (doc.y > 700) doc.addPage();
      doc.font("Helvetica-Bold").fontSize(13).text(section.title);
      doc.font("Helvetica").fontSize(9).fillColor("#4b5563").text(sectionStatus(section));
      doc.fillColor("#000000");
      doc.moveDown(0.25);

      if (!section.items.length) {
        addWrappedText(doc, section.emptyState);
        doc.moveDown(0.5);
        continue;
      }

      for (const item of section.items) {
        if (doc.y > 720) doc.addPage();
        doc.font("Helvetica-Bold").fontSize(10).text(item.label);
        doc.font("Helvetica").fontSize(8).fillColor("#4b5563").text(
          [item.timestamp || "Timestamp not recorded", sourceLabel(item.sourceCollection)].join(" | ")
        );
        doc.fillColor("#000000");
        addWrappedText(doc, item.description);
        doc.moveDown(0.35);
      }
      doc.moveDown(0.35);
    }

    doc.end();
  });
}
