export const PORTFOLIO_SCORE_DECLINE_ALERT_THRESHOLD = 4;
export const RESOLUTION_STALE_HIGH_THRESHOLD_MS = 24 * 60 * 60 * 1000;
export const RESOLUTION_STALE_CRITICAL_THRESHOLD_MS = 48 * 60 * 60 * 1000;
export const REPEATED_EXCEPTION_THRESHOLD = 2;
