import PDFDocument from "pdfkit";
import { composeScheduleALegalDocument } from "../../lib/legalDocuments/scheduleAComposition";
import type { LeaseDraftCore } from "../leaseDraftsService";

function nonEmpty(value: string): string {
  return value.trim() || "Not specified";
}

export async function generateScheduleAPdfBuffer(input: {
  draftId: string;
  draft: LeaseDraftCore;
  landlordDisplayName: string;
  tenantDisplayNames: string[];
  propertyAddressLine: string;
  unitLabel: string;
}): Promise<Buffer> {
  const documentDefinition = composeScheduleALegalDocument(input);
  const doc = new PDFDocument({ size: "LETTER", margin: 54 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111827");
  doc.text("Schedule A - Additional Terms");
  doc.moveDown(0.2);
  doc.font("Helvetica").fontSize(10).fillColor("#4b5563");
  doc.text("Nova Scotia Form P addendum");
  doc.text(`Template version: ${documentDefinition.metadata.version}`);
  doc.moveDown(0.7);

  const leaseSummary = documentDefinition.sections.find((section) => section.id === "lease-summary");
  const term = documentDefinition.sections.find((section) => section.id === "term");
  const payments = documentDefinition.sections.find((section) => section.id === "payments");
  const additionalClauses = documentDefinition.sections.find((section) => section.id === "additional-clauses");
  const fieldByKey = new Map(
    [...(term?.fields || []), ...(payments?.fields || [])].map((field) => [field.key, field])
  );
  const termAndPaymentFields = [
    fieldByKey.get("termType"),
    fieldByKey.get("startDate"),
    fieldByKey.get("endDate"),
    fieldByKey.get("baseRent"),
    fieldByKey.get("parking"),
    fieldByKey.get("rentDueDay"),
    fieldByKey.get("paymentMethod"),
    fieldByKey.get("deposit"),
  ].filter(Boolean) as Array<{ label: string; value: string }>;

  const drawFieldSection = (title: string, fields: Array<{ label: string; value: string }>) => {
    doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827");
    doc.text(title);
    doc.moveDown(0.3);
    doc.font("Helvetica").fontSize(10).fillColor("#111827");
    fields.forEach((field) => {
      doc.text(`${field.label}: ${nonEmpty(field.value)}`);
    });
    doc.moveDown(0.7);
  };

  drawFieldSection("Lease Summary", leaseSummary?.fields || []);
  drawFieldSection("Term and Payment Details", termAndPaymentFields);

  doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827");
  doc.text("Additional Clauses");
  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(10).fillColor("#111827");
  const clauseText = additionalClauses?.body || "No additional clauses provided.";
  doc.text(clauseText, { width: doc.page.width - doc.page.margins.left - doc.page.margins.right });

  doc.moveDown(1.2);
  doc.font("Helvetica").fontSize(9).fillColor("#6b7280");
  doc.text(`Generated by RentChain - ${new Date().toISOString()}`);

  doc.end();
  await new Promise<void>((resolve, reject) => {
    doc.on("end", resolve);
    doc.on("error", reject);
  });
  return Buffer.concat(chunks);
}
