import PDFDocument from "pdfkit";
import type { LeaseDraftCore } from "../leaseDraftsService";

const NS_TEMPLATE_VERSION = "ns-schedule-a-v1";

function formatMoney(cents: number | null | undefined): string {
  const value = Number(cents || 0) / 100;
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    minimumFractionDigits: 2,
  }).format(value);
}

function termLabel(termType: LeaseDraftCore["termType"]): string {
  if (termType === "fixed") return "Fixed term";
  if (termType === "year-to-year") return "Year-to-year";
  return "Month-to-month";
}

function nonEmpty(value: string): string {
  return value.trim() || "Not specified";
}

export async function generateScheduleAPdfBuffer(input: {
  draftId: string;
  draft: LeaseDraftCore;
  landlordDisplayName: string;
  tenantDisplayNames: string[];
  propertyAddressLine: string;
  unitLabel: string;
}): Promise<Buffer> {
  const { draft } = input;
  const doc = new PDFDocument({ size: "LETTER", margin: 54 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));

  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111827");
  doc.text("Schedule A - Additional Terms");
  doc.moveDown(0.2);
  doc.font("Helvetica").fontSize(10).fillColor("#4b5563");
  doc.text("Nova Scotia Form P addendum");
  doc.text(`Template version: ${NS_TEMPLATE_VERSION}`);
  doc.moveDown(0.7);

  doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827");
  doc.text("Lease Summary");
  doc.moveDown(0.3);

  doc.font("Helvetica").fontSize(10).fillColor("#111827");
  doc.text(`Landlord: ${nonEmpty(input.landlordDisplayName || "Landlord")}`);
  doc.text(`Tenant(s): ${nonEmpty(input.tenantDisplayNames.join(", ") || "Tenant")}`);
  doc.text(`Property: ${nonEmpty(input.propertyAddressLine || draft.propertyId)}`);
  doc.text(`Unit: ${nonEmpty(input.unitLabel || draft.unitId)}`);
  doc.text(`Draft ID: ${nonEmpty(input.draftId)}`);
  doc.moveDown(0.7);

  doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827");
  doc.text("Term and Payment Details");
  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(10).fillColor("#111827");
  doc.text(`Term type: ${termLabel(draft.termType)}`);
  doc.text(`Start date: ${nonEmpty(draft.startDate)}`);
  doc.text(`End date: ${nonEmpty(draft.endDate || "")}`);
  doc.text(`Base rent: ${formatMoney(draft.baseRentCents)}`);
  doc.text(`Parking: ${formatMoney(draft.parkingCents)}`);
  doc.text(`Rent due day: ${draft.dueDay}`);
  doc.text(`Payment method: ${nonEmpty(draft.paymentMethod)}`);
  doc.text(
    `Deposit: ${draft.depositCents != null ? formatMoney(draft.depositCents) : "Not specified"}`
  );
  doc.moveDown(0.7);

  doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827");
  doc.text("Additional Clauses");
  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(10).fillColor("#111827");
  const clauseText = draft.additionalClauses?.trim() || "No additional clauses provided.";
  doc.text(clauseText, { width: doc.page.width - doc.page.margins.left - doc.page.margins.right });

  doc.moveDown(1.2);
  doc.font("Helvetica").fontSize(9).fillColor("#6b7280");
  doc.text(`Generated by RentChain - ${new Date().toISOString()}`);

  doc.end();
  await new Promise<void>((resolve, reject) => {
    doc.on("end", resolve);
    doc.on("error", reject);
  });
  return Buffer.concat(chunks);
}
