substitutions:
  _REGION: us-central1
  _SERVICE: rentchain-landlord-api
  _REPO: rentchain-api
  _IMAGE: rentchain-landlord-api
  _IMAGE_TAG: "${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Debug environment snapshot
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euxo pipefail
        echo "==== ENV (first 120) ===="
        env | sort | sed -n '1,120p'
        echo "==== PWD/FILES ===="
        pwd
        ls -la

  # Install deps + build (fails fast on TS)
  - name: "node:20"
    entrypoint: "bash"
    dir: "rentchain-api"
    args:
      - "-lc"
      - |
        set -euxo pipefail
        npm install
        npm run build

  # Validate image tag before docker build
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ -z "${_IMAGE_TAG}" ]; then
          echo "ERROR: _IMAGE_TAG is empty. Provide --substitutions=_IMAGE_TAG=xxxx"
          exit 1
        fi
        echo "Using _IMAGE_TAG=${_IMAGE_TAG}"

  # Build Docker image from rentchain-api
  - name: "gcr.io/cloud-builders/docker"
    dir: rentchain-api
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_IMAGE_TAG}",
        ".",
      ]

  # Push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_IMAGE_TAG}",
      ]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euxo pipefail
        gcloud run deploy "${_SERVICE}" \
          --image "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_IMAGE_TAG}" \
          --region "${_REGION}" \
          --platform managed \
          --allow-unauthenticated
