steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy rentchain-landlord-api \
          --source ./rentchain-api \
          --region us-central1 \
          --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
YAML