import { CreditProvider, CreditProviderRequest, CreditProviderResult } from "./providerTypes";

class ProviderNotConfiguredError extends Error {
  code = "provider_not_configured";
}

function assertConfigured() {
  const apiKey = process.env.PROVIDER_A_API_KEY;
  const baseUrl = process.env.PROVIDER_A_BASE_URL;

  if (!apiKey || !baseUrl) {
    throw new ProviderNotConfiguredError("provider_not_configured");
  }

  return { apiKey, baseUrl };
}

type FetchInit = {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
  signal?: AbortSignal;
};

async function fetchWithTimeout(
  url: string,
  init: FetchInit,
  timeoutMs = 10000
) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...init, signal: controller.signal });
    return res;
  } finally {
    clearTimeout(timeout);
  }
}

export class ProviderA implements CreditProvider {
  async createReport(
    request: CreditProviderRequest
  ): Promise<CreditProviderResult> {
    const { apiKey, baseUrl } = assertConfigured();

    const url = `${baseUrl.replace(/\/$/, "")}/credit/report`;
    const body = JSON.stringify(request);

    const init = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body,
    };

    const response = await this.performRequestWithRetry(url, init);

    // NOTE: Replace this with the real provider response mapping.
    const raw = await response.json();

    return {
      providerName: "providerA",
      providerReferenceId:
        raw && raw.id ? raw.id : "providerA-unknown",
      score: raw && typeof raw.score === "number" ? raw.score : undefined,
      riskBand: raw && raw.riskBand ? raw.riskBand : undefined,
      highlights:
        raw && Array.isArray(raw.highlights) && raw.highlights.length
          ? raw.highlights
          : ["Credit report retrieved."],
      summaryText:
        raw && raw.summaryText
          ? raw.summaryText
          :
        "Credit report generated by providerA (response mapping placeholder).",
      rawPayload: raw || {},
      generatedAt: new Date().toISOString(),
    };
  }

  private async performRequestWithRetry(
    url: string,
    init: FetchInit
  ): Promise<Response> {
    const attempt = async (): Promise<Response> => {
      const res = await fetchWithTimeout(url, init, 10000);
      if (!res.ok) {
        const error: any = new Error(
          res.status === 401 || res.status === 403
            ? "provider_not_configured"
            : "provider_request_failed"
        );
        error.code = error.message;
        error.status = res.status;
        throw error;
      }
      return res;
    };

    try {
      return await attempt();
    } catch (err: any) {
      const status =
        err && err.status
          ? err.status
          : err && err.response && err.response.status
          ? err.response.status
          : undefined;
      if (status && status >= 500 && status < 600) {
        return attempt();
      }
      if (err && err.code === "provider_not_configured") {
        throw err;
      }
      throw err;
    }
  }
}

export { ProviderNotConfiguredError };
