import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ loadWorkspace: vi.fn(), loadStartContext: vi.fn() }));
vi.mock("@/api/occupancyReviewApi", async (importOriginal) => ({ ...(await importOriginal<any>()), getOccupancyReviewWorkspace: mocks.loadWorkspace }));
vi.mock("@/api/occupancyStartApi", () => ({ getOccupancyStartContext: mocks.loadStartContext }));
vi.mock("@/components/occupancy/ResolveOccupancyDrawer", () => ({ ResolveOccupancyDrawer: (props: any) => props.open ? <div role="dialog"><span>Existing Resolve Occupancy workflow</span><button onClick={props.onResolved}>Complete workflow</button></div> : null }));
vi.mock("@/components/occupancy/StartOccupancyDrawer", () => ({ StartOccupancyDrawer: (props: any) => <div role="dialog"><span>Server-authoritative Start Occupancy workflow</span><button onClick={props.onStarted}>Complete start</button></div> }));
import ReviewNeededPage, { reasonPresentation } from "./ReviewNeededPage";

const item = (overrides: Record<string, any> = {}) => ({ id: "review-1", scope: "unit", propertyId: "property-1", propertyName: "Harbour House", unitId: "unit-1", unitLabel: "Unit 1", tenantId: "tenant-1", tenantName: "Taylor Tenant", supportingLeaseId: null, candidateLeaseIds: ["lease-a", "lease-b"], canonicalState: { leaseTermState: null, occupancyState: "review_needed", tenantRelationshipState: "occupancy_unresolved", supportingLeaseId: null, reasons: ["MULTIPLE_CURRENT_LEASES"] }, reasons: ["MULTIPLE_CURRENT_LEASES"], severity: "high", category: "occupancy", action: "resolve_multiple_current", actionTarget: "/properties", stableSortKey: "a", ...overrides });
const response = (items = [item()]) => ({ ok: true, items, counts: { total: items.length, multipleCurrent: items.filter((row) => row.reasons.includes("MULTIPLE_CURRENT_LEASES")).length, occupancy: items.filter((row) => row.category === "occupancy").length, lease: items.filter((row) => row.category === "lease").length, signing: items.filter((row) => row.category === "signing").length, tenantRelationship: items.filter((row) => row.category === "tenant_relationship").length } });

describe("ReviewNeededPage", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.loadWorkspace.mockResolvedValue(response()); mocks.loadStartContext.mockResolvedValue({ context: { eligible: true } }); });
  afterEach(() => cleanup());
  const renderPage = () => render(<MemoryRouter><ReviewNeededPage /></MemoryRouter>);
  it("loads one server-authoritative workspace with summary counts and human reason copy", async () => { renderPage(); expect(await screen.findByText("Multiple current leases")).toBeInTheDocument(); expect(screen.getByLabelText("Review summary")).toHaveTextContent("1Total"); expect(screen.queryByText("MULTIPLE_CURRENT_LEASES")).not.toBeInTheDocument(); });
  it("renders a legitimate empty state", async () => { mocks.loadWorkspace.mockResolvedValue(response([])); renderPage(); expect(await screen.findByText("No canonical occupancy conflicts need review.")).toBeInTheDocument(); });
  it("fails closed without showing an all-clear on server error", async () => { mocks.loadWorkspace.mockRejectedValue(new Error("failed")); renderPage(); expect(await screen.findByRole("alert")).toHaveTextContent("No records have been treated as resolved"); expect(screen.queryByText("No canonical occupancy conflicts need review.")).not.toBeInTheDocument(); });
  it("opens the existing Resolve Occupancy workflow and refreshes only after success", async () => { renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Resolve occupancy" })); expect(screen.getByRole("dialog")).toHaveTextContent("Existing Resolve Occupancy workflow"); expect(mocks.loadWorkspace).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole("button", { name: "Complete workflow" })); await waitFor(() => expect(mocks.loadWorkspace).toHaveBeenCalledTimes(2)); });
  it("routes an ordinary occupancy mismatch through the existing Resolve Occupancy workflow", async () => { mocks.loadWorkspace.mockResolvedValue(response([item({ action: "resolve_occupancy", reasons: ["VACANT_WITH_CURRENT_LEASE"], candidateLeaseIds: [] })])); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Resolve occupancy" })); expect(screen.getByRole("dialog")).toHaveTextContent("Existing Resolve Occupancy workflow"); });
  it("uses bounded landlord language for lease-context mismatch and keeps it in Resolve Occupancy", async () => { mocks.loadWorkspace.mockResolvedValue(response([item({ action: "resolve_occupancy", reasons: ["CURRENT_LEASE_CONTEXT_MISMATCH"], candidateLeaseIds: [] })])); renderPage(); expect(await screen.findByText("Lease and occupancy links don't match")).toBeInTheDocument(); expect(screen.queryByText("CURRENT_LEASE_CONTEXT_MISMATCH")).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Resolve occupancy" })); expect(screen.getByRole("dialog")).toHaveTextContent("Existing Resolve Occupancy workflow"); });
  it("routes a sole supporting vacant-current lease to Start Occupancy and refreshes after success", async () => { mocks.loadWorkspace.mockResolvedValue(response([item({ action: "resolve_occupancy", reasons: ["VACANT_WITH_CURRENT_LEASE"], supportingLeaseId: "lease-a", candidateLeaseIds: ["lease-a"] })])); renderPage(); fireEvent.click(await screen.findByRole("button", { name: "Start Occupancy" })); expect(screen.getByRole("dialog")).toHaveTextContent("Server-authoritative Start Occupancy workflow"); fireEvent.click(screen.getByRole("button", { name: "Complete start" })); await waitFor(() => expect(mocks.loadWorkspace).toHaveBeenCalledTimes(2)); });
  it("does not expose Start Occupancy when the server context is ineligible", async () => { mocks.loadStartContext.mockResolvedValue({ context: { eligible: false } }); mocks.loadWorkspace.mockResolvedValue(response([item({ action: "resolve_occupancy", reasons: ["VACANT_WITH_CURRENT_LEASE"], supportingLeaseId: "lease-a", candidateLeaseIds: ["lease-a"] })])); renderPage(); await screen.findByText("Vacancy conflicts with a current lease"); await waitFor(() => expect(mocks.loadStartContext).toHaveBeenCalledWith("lease-a")); expect(screen.queryByRole("button", { name: "Start Occupancy" })).not.toBeInTheDocument(); });
  it("routes legitimate signing review to the existing pending-signing workspace", async () => { mocks.loadWorkspace.mockResolvedValue(response([item({ action: "continue_signing", actionTarget: "/leases?view=pending-signing&leaseId=lease-a", category: "signing", reasons: ["LEASE_EXECUTION_INCOMPLETE"], supportingLeaseId: "lease-a" })])); renderPage(); expect(await screen.findByRole("link", { name: "Continue signing" })).toHaveAttribute("href", "/leases?view=pending-signing&leaseId=lease-a"); });
  it("renders review-only items without an unsafe mutation button", async () => { mocks.loadWorkspace.mockResolvedValue(response([item({ id: "review-only", action: "review_only", actionTarget: null, reasons: ["ENDED_LEASE_CANNOT_SUPPORT_OCCUPANCY"], category: "lease" })])); renderPage(); expect(await screen.findByText("Ended lease conflicts with occupancy")).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /resolve|end lease|fix/i })).not.toBeInTheDocument(); });
  it("supports all primary category filters without removing source items", async () => { mocks.loadWorkspace.mockResolvedValue(response([item(), item({ id: "lease", category: "lease", action: "review_lease", actionTarget: "/leases", reasons: ["PAST_LEASE_CANNOT_SUPPORT_OCCUPANCY"] }), item({ id: "signing", category: "signing", action: "continue_signing", actionTarget: "/leases", reasons: ["LEASE_EXECUTION_INCOMPLETE"] }), item({ id: "tenant", category: "tenant_relationship", action: "review_tenant_relationship", actionTarget: "/tenants", reasons: ["TENANT_CURRENT_WITHOUT_CURRENT_LEASE"] })])); renderPage(); const filters = await screen.findByLabelText("Review filters"); fireEvent.click(within(filters).getByRole("button", { name: "Signing" })); expect(screen.getByText("Lease signing is incomplete")).toBeInTheDocument(); expect(screen.queryByText("Multiple current leases")).not.toBeInTheDocument(); });
  it("uses a safe unknown-reason fallback", () => expect(reasonPresentation("FUTURE_REASON")).toMatchObject({ title: "Occupancy record needs review" }));
  it("has human-readable presentation for every canonical reason", () => { const reasons = ["MULTIPLE_CURRENT_LEASES", "INVALID_LEASE_DATE_RANGE", "CURRENT_LEASE_CONTEXT_MISMATCH", "DRAFT_LEASE_CANNOT_SUPPORT_OCCUPANCY", "UPCOMING_LEASE_CANNOT_SUPPORT_OCCUPANCY", "PAST_LEASE_CANNOT_SUPPORT_OCCUPANCY", "ENDED_LEASE_CANNOT_SUPPORT_OCCUPANCY", "LEASE_EXECUTION_INCOMPLETE", "OCCUPIED_WITHOUT_CURRENT_LEASE", "VACANT_WITH_CURRENT_LEASE", "STALE_CURRENT_LEASE_POINTER", "TENANT_CURRENT_WITHOUT_CURRENT_LEASE"]; for (const reason of reasons) expect(reasonPresentation(reason).title).not.toBe("Occupancy record needs review"); });
  it("does not duplicate rows", async () => { renderPage(); expect(await screen.findAllByRole("article")).toHaveLength(1); });
});
