import { Application } from "express";

import dashboardRoutes from "./routes/dashboard";
import tenantDetailsRoutes from "./routes/tenantDetailsRoutes";
import paymentsRoutes from "./routes/paymentsRoutes";
import paymentListRoutes from "./routes/paymentListRoutes";
import leaseRoutes from "./routes/leaseRoutes";
import aiInsightsRoutes from "./routes/aiInsightsRoutes";
import ledgerRoutes from "./routes/ledgerRoutes";
import blockchainRoutes from "./routes/blockchainRoutes";
import blockchainVerifyRoutes from "./routes/blockchainVerifyRoutes";
import applicationsRoutes from "./routes/applicationsRoutes";
import tenantOnboardRoutes from "./routes/tenantOnboardRoutes";
import tenantLedgerRoutes from "./routes/tenantLedgerRoutes";
import creditReportRoutes from "./routes/creditReportRoutes";
import propertiesRoutes from "./routes/propertiesRoutes";
import auditEventsRoutes from "./routes/auditEventsRoutes";
import screeningRoutes from "./routes/screeningRoutes";
import stripeWebhookRoutes from "./routes/stripeWebhookRoutes";
import adminScreeningsRoutes from "./routes/adminScreeningsRoutes";
import rentReportingRoutes from "./routes/rentReportingRoutes";
import dashboardAiRoutes from "./routes/dashboardAiRoutes";
import applicationsConversionRoutes from "./routes/applicationsConversionRoutes";
import actionRequestsRoutes from "./routes/actionRequestsRoutes";
import reputationRoutes from "./routes/reputationRoutes";
import actionRequestsDevRoutes from "./routes/actionRequestsDevRoutes";
import actionRequestsRecomputeRoutes from "./routes/actionRequestsRecomputeRoutes";
import authDebugRoutes from "./routes/authDebugRoutes";
import devAuthRoutes from "./routes/devAuthRoutes";
import devDiagnosticsRoutes from "./routes/devDiagnosticsRoutes";

export function mountDevRoutes(app: Application) {
  // keep your existing mount paths exactly as they are today in app.ts
  app.use("/api/dashboard", dashboardRoutes);
  app.use("/api", tenantDetailsRoutes);
  app.use("/api/payments", paymentsRoutes);
  app.use("/api/payment-list", paymentListRoutes);
  app.use("/api/leases", leaseRoutes);
  app.use("/api/ai", aiInsightsRoutes);
  app.use("/api/ledger", ledgerRoutes);
  app.use("/api/blockchain", blockchainRoutes);
  app.use("/api/blockchain", blockchainVerifyRoutes);
  app.use("/api/applications", applicationsRoutes);
  app.use("/api/tenant-onboard", tenantOnboardRoutes);
  app.use("/api/tenant-ledger", tenantLedgerRoutes);
  app.use("/api/credit-report", creditReportRoutes);
  app.use("/api/properties", propertiesRoutes);
  app.use("/api/audit-events", auditEventsRoutes);
  app.use("/api/screening", screeningRoutes);
  app.use("/api/stripe", stripeWebhookRoutes);
  app.use("/api/admin/screenings", adminScreeningsRoutes);
  app.use("/api/rent-reporting", rentReportingRoutes);
  app.use("/api/dashboard-ai", dashboardAiRoutes);
  app.use("/api/applications-conversion", applicationsConversionRoutes);
  app.use("/api/action-requests", actionRequestsRoutes);
  app.use("/api/reputation", reputationRoutes);
  app.use("/api/action-requests-dev", actionRequestsDevRoutes);
  app.use("/api/action-requests-recompute", actionRequestsRecomputeRoutes);
  app.use("/api/auth-debug", authDebugRoutes);
  app.use("/api/dev-auth", devAuthRoutes);
  app.use("/api/dev", devDiagnosticsRoutes);
}
